services:
  postgres_db:
    networks: [main]
    container_name: postgres
    image: pgvector/pgvector:pg17-trixie@sha256:602e2bfa1ac026aedfd34bcef2154c8112b98d709bd692cba28f40a0c7ba809e
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: "this-is-a-very-secure-password"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "{{ base_directory }}/postgresql-data:/var/lib/postgresql/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  main:
    external: true
  wgnet:
    external: true