services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest@sha256:163e7351430a95d550d5b1bb958527edc1eff115eb013ca627f3545a192e853f
    container_name: zigbee2mqtt
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=HostRegexp(`zigbee2mqtt.{any:.+}`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=websecure"
      - "traefik.http.routers.zigbee2mqtt.tls.certresolver=letsencrypt"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
    volumes:
      - "{{ base_directory }}/zigbee2mqtt-data:/app/data"
      - /run/udev:/run/udev:ro
    user: 1000:1000
    group_add:
      - dialout
    devices:
      - {{ secret.zigbee_device_id }}:/dev/ttyUSB0
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - main


networks:
  main:
    external: true